version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    networks:
      - mynetwork
    expose:
      - "80" 
    command: ["uvicorn", "webapp.main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #:ro
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./certs:/etc/ssl/certs
#      - ./certs:/etc/ssl/private
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
